### PR TITLE
Hide unnecessary usage on Sonolark error

### LINKED ISSUE #138: Hide unnecessary usage on sonolark error
Errors are too verbose; i.e.

```
Error: Traceback (most recent call last):
  script.star:12:6: in <toplevel>
  script.star:3:5: in check
Error: NoneType value is not iterable
Usage:
  sonolark [flags]
  sonolark [command]

Available Commands:
  completion  Generate the
...
...
```

The usage should be disabled on error.

### PR DESCRIPTION
**Pull request by andrewyunt**
Fixes #138

### CODE REVIEW

File: sonolark/cmd/root.go [hunk 1]
```diff
@@ -73,19 +74,18 @@ func getRootCmd(env map[string]string) *cobra.Command {
 
 			predeclared, err := getLibraryFuncs(in.KubeConfigPath, env)
 			if err != nil {
-				return nil
+				return
```
Comment (johnSchnake) [inline sonolark/cmd/root.go:77]: We returned nil here? That seems like it must have been a temporary thing that never got repaired. We obviously need to return some message here.

File: sonolark/cmd/root.go [hunk 2]
```diff
@@ -73,19 +74,18 @@ func getRootCmd(env map[string]string) *cobra.Command {
...
 			}
 
 			_, err = starlark.ExecFile(thread, in.Filename, nil, *predeclared)
 			if err != nil {
 				if evalErr, ok := err.(*starlark.EvalError); ok {
 					sonobuoy.FailTest(thread, evalErr.Backtrace())
-					return errors.New(evalErr.Backtrace())
+					fmt.Println(errors.New(evalErr.Backtrace()))
```
Comment (johnSchnake) [inline sonolark/cmd/root.go:84]: When printing errors, print to os.Stderr rather than os.Stdout. Not sure if this is followed in many places but it is good practice

File: sonolark/cmd/root.go [hunk 3]
```diff
@@ -62,7 +63,7 @@ func getRootCmd(env map[string]string) *cobra.Command {
 	root := &cobra.Command{
 		Use:   "sonolark",
 		Short: "Sonolark is a tool which allows users to easily build scripts using the Starlark language on top of our library of useful functions including assertions, Kubernetes API access, and more.",
-		RunE: func(cmd *cobra.Command, args []string) error {
+		Run: func(cmd *cobra.Command, args []string) {
```
Comment (johnSchnake) [inline sonolark/cmd/root.go:66]: Rather than changing this to `Run` and handling each case, I would recommend leaving it as `RunE` and updating the method that executes this.

That way you only have to handle all the errors in one place.

Currently we have:

```
	err := getRootCmd(getEnvs()).Execute()
	if err != nil {
		os.Exit(1)
	}
```
and you'd just need to add the printing.

Otherwise, I think an unintended consequence of this is that you're going to be reporting an error to the user but the exit code of the process is probably always 0 since an error is never returned. So yes, you're hiding the usage, but because you've told it you never encounter an error.

The exit code is something not particularly documented or tested, but users will expect a non-zero exit code on failure. K8s will even recognize that as a failure and thereby trigger different states in the containers etc and people use that to script around as well.

**Review by johnSchnake — CHANGES_REQUESTED** [review]
